spring.application.name=VendaSys

# Importa o arquivo .env
spring.config.import=optional:file:${user.dir}/.env[.properties]

# Perfil padrão (pode ser dev ou prod)
spring.profiles.active=${SPRING_PROFILE:dev}